####
GET http://localhost:5216/api/v01/Invitation/GetMyInvitations
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyZjY3M2FkOS02OTEzLTQ2ZDAtOWI0NC1kNTE3YzU2MTFjOGMiLCJqdGkiOiI1NjdiOWRlN2Y2MGI0ZmUzOWUxNzI0NmI5NWUxZTIzNSIsIm5hbWUiOiJhbGkiLCJyb2xlIjoiU3Rld2FyZCIsIm5iZiI6MTc3ODQyOTAyMywiZXhwIjoxNzc4NDI5OTIzLCJpc3MiOiJodHRwczovL2VtYmVyLm5nbyIsImF1ZCI6Imh0dHBzOi8vZW1iZXIubmdvIn0.H7CYolhaaYgQb7PfblN_FZsLrrXDE6Iat51bKkAos9E
