// <auto-generated />
using System;
using Ember.WebServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ember.WebServer.Migrations
{
    [DbContext(typeof(EmberDbContext))]
    [Migration("20260201040243_InitiateDatabase")]
    partial class InitiateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ember.WebServer.Areas.Knowledge.Entities.Collection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("Collections");
                });

            modelBuilder.Entity("Ember.WebServer.Areas.Knowledge.Entities.CollectionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContentId")
                        .HasColumnType("uuid");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId");

                    b.HasIndex("ContentId");

                    b.ToTable("CollectionItems");
                });

            modelBuilder.Entity("Ember.WebServer.Areas.Knowledge.Entities.Content", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ContentFormatId")
                        .HasColumnType("integer");

                    b.Property<int>("ContentTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("ContentVisibilityId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Data")
                        .HasColumnType("text");

                    b.Property<int>("FormatVersion")
                        .HasColumnType("integer");

                    b.Property<Guid>("Identifier")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ParentContentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RemovedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ContentFormatId");

                    b.HasIndex("ContentTypeId");

                    b.HasIndex("ContentVisibilityId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ParentContentId");

                    b.ToTable("Contents");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3173c43b-b415-4d45-a002-7c7d7253bf1b"),
                            ContentFormatId = 1,
                            ContentTypeId = 1,
                            ContentVisibilityId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 31, 14, 44, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            CreatedByUserId = new Guid("2f673ad9-6913-46d0-9b44-d517c5611c8c"),
                            Data = "# Welcome to Ember!\n\nEmber is an attempt to give users ownership of their online activities.\nAn online service that does not seek profit, would give users tools they need to find the data they want,\ninteract with the platform in ways that make sense to their use cases,\nkeep the user in control, not at the mercy of intentionally limited UX and engagement-maximizing algorithms.\n\nTransparency builds dependable trust, amongst users, and between users and the platform.\nWith time, we can create tools that provide users with a measure of trustworthiness of content and its creators.\nThese measures should reflect each user's values and priorities, not those imposed by a centralized authority.\n\nThe premise is that a confused user is more likely to make decisions that are not in their best interest.\n\nWe'll start with the simplest tools: a place you can write and share pieces of content.\nWith that, conversations around Ember development can be hosted on the platform itself.\n\nEmber is an attempt to bring back how trust shaped human interactions in small communities,\nbut we lost that when we moved to the global village, and platforms that seek profit at the expense societal good.\n\nMuch more details to be shared as we build more features.\n",
                            FormatVersion = 1,
                            Identifier = new Guid("3fee5a19-69e4-4c65-81fe-8d9de9c11539"),
                            IsActive = true,
                            Title = "Welcome to Ember",
                            Version = 1
                        });
                });

            modelBuilder.Entity("Ember.WebServer.Areas.Knowledge.Entities.ContentFormat", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ContentFormat");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Markdown"
                        });
                });

            modelBuilder.Entity("Ember.WebServer.Areas.Knowledge.Entities.ContentInteraction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDisliked")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLiked")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Recommend")
                        .HasColumnType("boolean");

                    b.Property<bool>("RemindLaterList")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ContentId");

                    b.HasIndex("UserId");

                    b.ToTable("ContentInteractions");
                });

            modelBuilder.Entity("Ember.WebServer.Areas.Knowledge.Entities.ContentTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ContentId");

                    b.HasIndex("TagId");

                    b.ToTable("ContentTags");
                });

            modelBuilder.Entity("Ember.WebServer.Areas.Knowledge.Entities.ContentType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ContentTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Paragraph"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Section"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Article"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Image"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Video"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Audio"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Link"
                        },
                        new
                        {
                            Id = 8,
                            Name = "InteractiveElement"
                        },
                        new
                        {
                            Id = 9,
                            Name = "CodeSnippet"
                        },
                        new
                        {
                            Id = 10,
                            Name = "ExplorableDataset"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Comment"
                        });
                });

            modelBuilder.Entity("Ember.WebServer.Areas.Knowledge.Entities.ContentVisibility", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ContentVisibilities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Public"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Private"
                        },
                        new
                        {
                            Id = 3,
                            Name = "VisibleToSpecificPeople"
                        },
                        new
                        {
                            Id = 4,
                            Name = "VisibleByCriteria"
                        },
                        new
                        {
                            Id = 5,
                            Name = "ScheduledRollout"
                        });
                });

            modelBuilder.Entity("Ember.WebServer.Areas.Knowledge.Entities.RelatedContent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RelatedContentId")
                        .HasColumnType("uuid");

                    b.Property<int>("RelatedContentTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ContentId");

                    b.HasIndex("RelatedContentId");

                    b.HasIndex("RelatedContentTypeId");

                    b.ToTable("RelatedContents");
                });

            modelBuilder.Entity("Ember.WebServer.Areas.Knowledge.Entities.RelatedContentType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RelatedContentTypes");
                });

            modelBuilder.Entity("Ember.WebServer.Areas.Knowledge.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Ember.WebServer.Data.ActionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<string>("NewValues")
                        .HasColumnType("text");

                    b.Property<string>("OldValues")
                        .HasColumnType("text");

                    b.Property<int>("Owner")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("PurgingTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.HasIndex("UserId");

                    b.ToTable("ActionLogs");
                });

            modelBuilder.Entity("Ember.WebServer.Data.BadgeDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("DefaultValue")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsFractional")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsNumeric")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MaxValue")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MinValue")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BadgeDefinitions");
                });

            modelBuilder.Entity("Ember.WebServer.Data.DataOwnership", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LogOwnerships");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "System"
                        },
                        new
                        {
                            Id = 2,
                            Name = "User"
                        });
                });

            modelBuilder.Entity("Ember.WebServer.Data.EmberRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f883569f-2494-4328-95a9-e76a2b6ff143"),
                            Name = "Root",
                            NormalizedName = "Root"
                        },
                        new
                        {
                            Id = new Guid("5e4b79a1-afe1-4e79-a4e1-ee1b86e4ce33"),
                            Name = "Owner",
                            NormalizedName = "OWNER"
                        },
                        new
                        {
                            Id = new Guid("5e848956-8a01-4816-be8d-d6a6b7091cf3"),
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = new Guid("b373f8c6-b1b9-4097-98e1-46a881e5484d"),
                            Name = "Creator",
                            NormalizedName = "CREATOR"
                        },
                        new
                        {
                            Id = new Guid("a03c7114-423e-47e1-a280-6ba824c25828"),
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Ember.WebServer.Data.EmberRoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Ember.WebServer.Data.EmberUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<int>("BirthYear")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Jurisdiction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("6c0a35b2-23c4-44a3-8e13-161285b0f9db"),
                            AccessFailedCount = 0,
                            BirthYear = 0,
                            ConcurrencyStamp = "a5405995-3314-4821-be2f-17ddabd54fbf",
                            EmailConfirmed = true,
                            FullName = "System User",
                            Jurisdiction = "Canada",
                            LockoutEnabled = false,
                            NormalizedUserName = "SYSTEM",
                            PhoneNumberConfirmed = true,
                            TwoFactorEnabled = false,
                            UserName = "System"
                        },
                        new
                        {
                            Id = new Guid("2f673ad9-6913-46d0-9b44-d517c5611c8c"),
                            AccessFailedCount = 0,
                            BirthYear = 0,
                            ConcurrencyStamp = "2aaf7da4-ce97-4efb-a069-55ff3c131465",
                            EmailConfirmed = true,
                            FullName = "Alireza Haghshenas",
                            Jurisdiction = "Canada",
                            LockoutEnabled = false,
                            NormalizedUserName = "ALI",
                            PhoneNumberConfirmed = true,
                            TwoFactorEnabled = false,
                            UserName = "ali"
                        });
                });

            modelBuilder.Entity("Ember.WebServer.Data.EmberUserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Ember.WebServer.Data.EmberUserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PlatformSectionId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("PlatformSectionId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("6c0a35b2-23c4-44a3-8e13-161285b0f9db"),
                            RoleId = new Guid("f883569f-2494-4328-95a9-e76a2b6ff143"),
                            Id = new Guid("43510e33-41e3-45bb-96c3-be52af6b9c3b")
                        },
                        new
                        {
                            UserId = new Guid("2f673ad9-6913-46d0-9b44-d517c5611c8c"),
                            RoleId = new Guid("5e4b79a1-afe1-4e79-a4e1-ee1b86e4ce33"),
                            Id = new Guid("072c2bb6-f216-4c07-8e4c-f6b3abb05770")
                        });
                });

            modelBuilder.Entity("Ember.WebServer.Data.EmberUserToken", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Ember.WebServer.Data.FinancialModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FinancialModels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A financial model where the organization does not distribute profits to owners or shareholders.",
                            Name = "Non-Profit"
                        },
                        new
                        {
                            Id = 2,
                            Description = "A financial model where the organization aims to generate profit for its owners or shareholders.",
                            Name = "For-Profit"
                        });
                });

            modelBuilder.Entity("Ember.WebServer.Data.InteractionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<string>("InteractionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Owner")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("PurgingTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RelativeUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("InteractionLogs");
                });

            modelBuilder.Entity("Ember.WebServer.Data.PlatformSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FinancialModelId")
                        .HasColumnType("integer");

                    b.Property<bool>("InheritRoles")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentPlatformSectionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentSectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatorUserId");

                    b.HasIndex("FinancialModelId");

                    b.HasIndex("ParentPlatformSectionId");

                    b.ToTable("PlatformSections");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d04c1e89-a4c8-450b-8608-84f35415fd39"),
                            CreatorUserId = new Guid("2f673ad9-6913-46d0-9b44-d517c5611c8c"),
                            Description = "The Ember Foundation, the non-profit organization that drives all other Ember projects.",
                            FinancialModelId = 1,
                            InheritRoles = false,
                            Name = "Ember Foundation",
                            Url = "/"
                        });
                });

            modelBuilder.Entity("Ember.WebServer.Data.ProcessLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CodePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<string>("Parameters")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("PurgingTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.ToTable("ProcessLogs");
                });

            modelBuilder.Entity("Ember.WebServer.Data.RequestLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BaseUri")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Payload")
                        .HasColumnType("text");

                    b.Property<string>("QueryString")
                        .HasColumnType("text");

                    b.Property<string>("RelativeUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("TotalRequestSize")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RequestLogs");
                });

            modelBuilder.Entity("Ember.WebServer.Data.ResponseLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("ProcessingTime")
                        .HasColumnType("interval");

                    b.Property<DateTimeOffset?>("PurgingTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RequestLogId")
                        .HasColumnType("uuid");

                    b.Property<int>("ResponseStatusCode")
                        .HasColumnType("integer");

                    b.Property<long>("TotalResponseSize")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RequestLogId");

                    b.ToTable("ResponseLogs");
                });

            modelBuilder.Entity("Ember.WebServer.Data.Testimonial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool?>("ApprovesBooleanBadge")
                        .HasColumnType("boolean");

                    b.Property<Guid>("BadgeDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ForUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("FromTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<decimal?>("NumericBadgeValue")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset?>("ToTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BadgeDefinitionId");

                    b.HasIndex("ByUserId");

                    b.HasIndex("ForUserId");

                    b.ToTable("Testimonials");
                });

            modelBuilder.Entity("Ember.WebServer.Data.UserBadgeValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BadgeDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("FromTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ToTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("BadgeDefinitionId");

                    b.HasIndex("UserId");

                    b.ToTable("UserBadgeValues");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Ember.WebServer.Areas.Knowledge.Entities.Collection", b =>
                {
                    b.HasOne("Ember.WebServer.Data.EmberUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("Ember.WebServer.Areas.Knowledge.Entities.CollectionItem", b =>
                {
                    b.HasOne("Ember.WebServer.Areas.Knowledge.Entities.Collection", "Collection")
                        .WithMany()
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ember.WebServer.Areas.Knowledge.Entities.Content", "Content")
                        .WithMany()
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collection");

                    b.Navigation("Content");
                });

            modelBuilder.Entity("Ember.WebServer.Areas.Knowledge.Entities.Content", b =>
                {
                    b.HasOne("Ember.WebServer.Areas.Knowledge.Entities.ContentFormat", "ContentFormat")
                        .WithMany()
                        .HasForeignKey("ContentFormatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ember.WebServer.Areas.Knowledge.Entities.ContentType", "ContentType")
                        .WithMany()
                        .HasForeignKey("ContentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ember.WebServer.Areas.Knowledge.Entities.ContentVisibility", "ContentVisibility")
                        .WithMany()
                        .HasForeignKey("ContentVisibilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ember.WebServer.Data.EmberUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ember.WebServer.Areas.Knowledge.Entities.Content", "ParentContent")
                        .WithMany("ChildContents")
                        .HasForeignKey("ParentContentId");

                    b.Navigation("ContentFormat");

                    b.Navigation("ContentType");

                    b.Navigation("ContentVisibility");

                    b.Navigation("CreatedByUser");

                    b.Navigation("ParentContent");
                });

            modelBuilder.Entity("Ember.WebServer.Areas.Knowledge.Entities.ContentInteraction", b =>
                {
                    b.HasOne("Ember.WebServer.Areas.Knowledge.Entities.Content", "Content")
                        .WithMany()
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ember.WebServer.Data.EmberUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Content");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ember.WebServer.Areas.Knowledge.Entities.ContentTag", b =>
                {
                    b.HasOne("Ember.WebServer.Areas.Knowledge.Entities.Content", "Content")
                        .WithMany()
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ember.WebServer.Areas.Knowledge.Entities.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Content");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Ember.WebServer.Areas.Knowledge.Entities.RelatedContent", b =>
                {
                    b.HasOne("Ember.WebServer.Areas.Knowledge.Entities.Content", "Content")
                        .WithMany()
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ember.WebServer.Areas.Knowledge.Entities.Content", "RelatedContentItem")
                        .WithMany()
                        .HasForeignKey("RelatedContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ember.WebServer.Areas.Knowledge.Entities.RelatedContentType", "RelatedContentType")
                        .WithMany()
                        .HasForeignKey("RelatedContentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Content");

                    b.Navigation("RelatedContentItem");

                    b.Navigation("RelatedContentType");
                });

            modelBuilder.Entity("Ember.WebServer.Data.ActionLog", b =>
                {
                    b.HasOne("Ember.WebServer.Data.RequestLog", "Request")
                        .WithMany()
                        .HasForeignKey("RequestId");

                    b.HasOne("Ember.WebServer.Data.EmberUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Request");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ember.WebServer.Data.EmberRoleClaim", b =>
                {
                    b.HasOne("Ember.WebServer.Data.EmberRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ember.WebServer.Data.EmberUserLogin", b =>
                {
                    b.HasOne("Ember.WebServer.Data.EmberUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ember.WebServer.Data.EmberUserRole", b =>
                {
                    b.HasOne("Ember.WebServer.Data.PlatformSection", "PlatformSection")
                        .WithMany()
                        .HasForeignKey("PlatformSectionId");

                    b.HasOne("Ember.WebServer.Data.EmberRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ember.WebServer.Data.EmberUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlatformSection");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ember.WebServer.Data.EmberUserToken", b =>
                {
                    b.HasOne("Ember.WebServer.Data.EmberUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ember.WebServer.Data.InteractionLog", b =>
                {
                    b.HasOne("Ember.WebServer.Data.EmberUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ember.WebServer.Data.PlatformSection", b =>
                {
                    b.HasOne("Ember.WebServer.Data.EmberUser", "CreatorUser")
                        .WithMany()
                        .HasForeignKey("CreatorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ember.WebServer.Data.FinancialModel", "FinancialModel")
                        .WithMany()
                        .HasForeignKey("FinancialModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ember.WebServer.Data.PlatformSection", "ParentPlatformSection")
                        .WithMany()
                        .HasForeignKey("ParentPlatformSectionId");

                    b.Navigation("CreatorUser");

                    b.Navigation("FinancialModel");

                    b.Navigation("ParentPlatformSection");
                });

            modelBuilder.Entity("Ember.WebServer.Data.ProcessLog", b =>
                {
                    b.HasOne("Ember.WebServer.Data.RequestLog", "Request")
                        .WithMany()
                        .HasForeignKey("RequestId");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("Ember.WebServer.Data.RequestLog", b =>
                {
                    b.HasOne("Ember.WebServer.Data.EmberUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ember.WebServer.Data.ResponseLog", b =>
                {
                    b.HasOne("Ember.WebServer.Data.RequestLog", "RequestLog")
                        .WithMany()
                        .HasForeignKey("RequestLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RequestLog");
                });

            modelBuilder.Entity("Ember.WebServer.Data.Testimonial", b =>
                {
                    b.HasOne("Ember.WebServer.Data.BadgeDefinition", "BadgeDefinition")
                        .WithMany()
                        .HasForeignKey("BadgeDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ember.WebServer.Data.EmberUser", "ByUser")
                        .WithMany()
                        .HasForeignKey("ByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ember.WebServer.Data.EmberUser", "ForUser")
                        .WithMany()
                        .HasForeignKey("ForUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BadgeDefinition");

                    b.Navigation("ByUser");

                    b.Navigation("ForUser");
                });

            modelBuilder.Entity("Ember.WebServer.Data.UserBadgeValue", b =>
                {
                    b.HasOne("Ember.WebServer.Data.BadgeDefinition", "BadgeDefinition")
                        .WithMany()
                        .HasForeignKey("BadgeDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ember.WebServer.Data.EmberUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BadgeDefinition");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Ember.WebServer.Data.EmberUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ember.WebServer.Areas.Knowledge.Entities.Content", b =>
                {
                    b.Navigation("ChildContents");
                });

            modelBuilder.Entity("Ember.WebServer.Data.EmberRole", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Ember.WebServer.Data.EmberUser", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
