// <auto-generated />
using System;
using Ember.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ember.Infrastructure.Migrations
{
    [DbContext(typeof(EmberDbContext))]
    [Migration("20260427042251_CollectionNameChange")]
    partial class CollectionNameChange
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ember.Domain.Data.ActionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<string>("NewValues")
                        .HasColumnType("text");

                    b.Property<string>("OldValues")
                        .HasColumnType("text");

                    b.Property<int>("Owner")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("PurgingTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.HasIndex("UserId");

                    b.ToTable("ActionLogs");
                });

            modelBuilder.Entity("Ember.Domain.Data.BadgeDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("DefaultValue")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsFractional")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsNumeric")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MaxValue")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MinValue")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BadgeDefinitions");
                });

            modelBuilder.Entity("Ember.Domain.Data.DataOwnership", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataOwnerships");
                });

            modelBuilder.Entity("Ember.Domain.Data.EmberRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Ember.Domain.Data.EmberRoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Ember.Domain.Data.EmberUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<int>("BirthYear")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Jurisdiction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Ember.Domain.Data.EmberUserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Ember.Domain.Data.EmberUserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PlatformSectionId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("PlatformSectionId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Ember.Domain.Data.EmberUserToken", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Ember.Domain.Data.FinancialModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FinancialModels");
                });

            modelBuilder.Entity("Ember.Domain.Data.InteractionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<string>("InteractionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Owner")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("PurgingTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RelativeUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("InteractionLogs");
                });

            modelBuilder.Entity("Ember.Domain.Data.Invitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AcceptedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InviteCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("InvitedByUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsInLegalAge")
                        .HasColumnType("boolean");

                    b.Property<string>("Jurisdiction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("RealName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AcceptedByUserId");

                    b.HasIndex("InviteCode")
                        .IsUnique();

                    b.HasIndex("InvitedByUserId");

                    b.ToTable("Invitations");
                });

            modelBuilder.Entity("Ember.Domain.Data.PlatformSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FinancialModelId")
                        .HasColumnType("integer");

                    b.Property<bool>("InheritRoles")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentPlatformSectionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentSectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatorUserId");

                    b.HasIndex("FinancialModelId");

                    b.HasIndex("ParentPlatformSectionId");

                    b.ToTable("PlatformSections");
                });

            modelBuilder.Entity("Ember.Domain.Data.ProcessLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CodePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<string>("Parameters")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("PurgingTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.ToTable("ProcessLogs");
                });

            modelBuilder.Entity("Ember.Domain.Data.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("text");

                    b.Property<string>("DeviceId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Ember.Domain.Data.RequestLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BaseUri")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Payload")
                        .HasColumnType("text");

                    b.Property<string>("QueryString")
                        .HasColumnType("text");

                    b.Property<string>("RelativeUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("TotalRequestSize")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RequestLogs");
                });

            modelBuilder.Entity("Ember.Domain.Data.ResponseLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("ProcessingTime")
                        .HasColumnType("interval");

                    b.Property<DateTimeOffset?>("PurgingTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RequestLogId")
                        .HasColumnType("uuid");

                    b.Property<int>("ResponseStatusCode")
                        .HasColumnType("integer");

                    b.Property<long>("TotalResponseSize")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RequestLogId");

                    b.ToTable("ResponseLogs");
                });

            modelBuilder.Entity("Ember.Domain.Data.Testimonial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool?>("ApprovesBooleanBadge")
                        .HasColumnType("boolean");

                    b.Property<Guid>("BadgeDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ByEmberUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ForEmberUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("FromTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<decimal?>("NumericBadgeValue")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset?>("ToTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BadgeDefinitionId");

                    b.HasIndex("ByEmberUserId");

                    b.HasIndex("ForEmberUserId");

                    b.ToTable("Testimonials");
                });

            modelBuilder.Entity("Ember.Domain.Data.UserBadgeValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BadgeDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmberUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("FromTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ToTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("BadgeDefinitionId");

                    b.HasIndex("EmberUserId");

                    b.ToTable("UserBadgeValues");
                });

            modelBuilder.Entity("Ember.Domain.EmberEntities.Content", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ContentFormatId")
                        .HasColumnType("integer");

                    b.Property<int>("ContentTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("ContentVisibilityId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("EmberUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("FormatVersion")
                        .HasColumnType("integer");

                    b.Property<Guid>("Identifier")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ParentContentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RemovedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.Property<string>("VisibilityCriteria")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ContentFormatId");

                    b.HasIndex("ContentTypeId");

                    b.HasIndex("ContentVisibilityId");

                    b.HasIndex("EmberUserId");

                    b.HasIndex("ParentContentId");

                    b.ToTable("Contents");
                });

            modelBuilder.Entity("Ember.Domain.EmberEntities.ContentCollection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("EmberUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EmberUserId");

                    b.ToTable("Collections");
                });

            modelBuilder.Entity("Ember.Domain.EmberEntities.ContentCollectionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ContentId")
                        .HasColumnType("uuid");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId");

                    b.HasIndex("ContentId");

                    b.ToTable("CollectionItems");
                });

            modelBuilder.Entity("Ember.Domain.EmberEntities.ContentFormat", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ContentFormats");
                });

            modelBuilder.Entity("Ember.Domain.EmberEntities.ContentInteraction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDisliked")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLiked")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Recommend")
                        .HasColumnType("boolean");

                    b.Property<bool>("RemindLaterList")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ContentId");

                    b.HasIndex("UserId");

                    b.ToTable("ContentInteractions");
                });

            modelBuilder.Entity("Ember.Domain.EmberEntities.ContentType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ContentTypes");
                });

            modelBuilder.Entity("Ember.Domain.EmberEntities.ContentVisibility", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ContentVisibilities");
                });

            modelBuilder.Entity("Ember.Domain.EmberEntities.RelatedContent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RelatedContentId")
                        .HasColumnType("uuid");

                    b.Property<int>("RelatedContentTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ContentId");

                    b.HasIndex("RelatedContentId");

                    b.HasIndex("RelatedContentTypeId");

                    b.ToTable("RelatedContents");
                });

            modelBuilder.Entity("Ember.Domain.EmberEntities.RelatedContentType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RelatedContentTypes");
                });

            modelBuilder.Entity("Ember.Domain.EmberEntities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EmberUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("HasConfidenceRate")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EmberUserId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Ember.Domain.EmberEntities.TagItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CollectionId")
                        .HasColumnType("uuid");

                    b.Property<byte?>("ConfidenceRate")
                        .HasColumnType("smallint");

                    b.Property<Guid?>("ContentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmberUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId");

                    b.HasIndex("ContentId");

                    b.HasIndex("EmberUserId");

                    b.HasIndex("TagId");

                    b.ToTable("ContentTags");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Ember.Domain.Data.ActionLog", b =>
                {
                    b.HasOne("Ember.Domain.Data.RequestLog", "Request")
                        .WithMany()
                        .HasForeignKey("RequestId");

                    b.HasOne("Ember.Domain.Data.EmberUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Request");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ember.Domain.Data.EmberRoleClaim", b =>
                {
                    b.HasOne("Ember.Domain.Data.EmberRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ember.Domain.Data.EmberUserLogin", b =>
                {
                    b.HasOne("Ember.Domain.Data.EmberUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ember.Domain.Data.EmberUserRole", b =>
                {
                    b.HasOne("Ember.Domain.Data.PlatformSection", "PlatformSection")
                        .WithMany()
                        .HasForeignKey("PlatformSectionId");

                    b.HasOne("Ember.Domain.Data.EmberRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ember.Domain.Data.EmberUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlatformSection");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ember.Domain.Data.EmberUserToken", b =>
                {
                    b.HasOne("Ember.Domain.Data.EmberUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ember.Domain.Data.InteractionLog", b =>
                {
                    b.HasOne("Ember.Domain.Data.EmberUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ember.Domain.Data.Invitation", b =>
                {
                    b.HasOne("Ember.Domain.Data.EmberUser", "AcceptedByUser")
                        .WithMany()
                        .HasForeignKey("AcceptedByUserId");

                    b.HasOne("Ember.Domain.Data.EmberUser", "InvitedByUser")
                        .WithMany()
                        .HasForeignKey("InvitedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcceptedByUser");

                    b.Navigation("InvitedByUser");
                });

            modelBuilder.Entity("Ember.Domain.Data.PlatformSection", b =>
                {
                    b.HasOne("Ember.Domain.Data.EmberUser", "CreatorUser")
                        .WithMany()
                        .HasForeignKey("CreatorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ember.Domain.Data.FinancialModel", "FinancialModel")
                        .WithMany()
                        .HasForeignKey("FinancialModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ember.Domain.Data.PlatformSection", "ParentPlatformSection")
                        .WithMany()
                        .HasForeignKey("ParentPlatformSectionId");

                    b.Navigation("CreatorUser");

                    b.Navigation("FinancialModel");

                    b.Navigation("ParentPlatformSection");
                });

            modelBuilder.Entity("Ember.Domain.Data.ProcessLog", b =>
                {
                    b.HasOne("Ember.Domain.Data.RequestLog", "Request")
                        .WithMany()
                        .HasForeignKey("RequestId");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("Ember.Domain.Data.RequestLog", b =>
                {
                    b.HasOne("Ember.Domain.Data.EmberUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ember.Domain.Data.ResponseLog", b =>
                {
                    b.HasOne("Ember.Domain.Data.RequestLog", "RequestLog")
                        .WithMany()
                        .HasForeignKey("RequestLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RequestLog");
                });

            modelBuilder.Entity("Ember.Domain.Data.Testimonial", b =>
                {
                    b.HasOne("Ember.Domain.Data.BadgeDefinition", "BadgeDefinition")
                        .WithMany()
                        .HasForeignKey("BadgeDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ember.Domain.Data.EmberUser", "ByEmberUser")
                        .WithMany()
                        .HasForeignKey("ByEmberUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ember.Domain.Data.EmberUser", "ForEmberUser")
                        .WithMany()
                        .HasForeignKey("ForEmberUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BadgeDefinition");

                    b.Navigation("ByEmberUser");

                    b.Navigation("ForEmberUser");
                });

            modelBuilder.Entity("Ember.Domain.Data.UserBadgeValue", b =>
                {
                    b.HasOne("Ember.Domain.Data.BadgeDefinition", "BadgeDefinition")
                        .WithMany()
                        .HasForeignKey("BadgeDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ember.Domain.Data.EmberUser", "EmberUser")
                        .WithMany()
                        .HasForeignKey("EmberUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BadgeDefinition");

                    b.Navigation("EmberUser");
                });

            modelBuilder.Entity("Ember.Domain.EmberEntities.Content", b =>
                {
                    b.HasOne("Ember.Domain.EmberEntities.ContentFormat", "ContentFormat")
                        .WithMany()
                        .HasForeignKey("ContentFormatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ember.Domain.EmberEntities.ContentType", "ContentType")
                        .WithMany()
                        .HasForeignKey("ContentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ember.Domain.EmberEntities.ContentVisibility", "ContentVisibility")
                        .WithMany()
                        .HasForeignKey("ContentVisibilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ember.Domain.Data.EmberUser", "EmberUser")
                        .WithMany()
                        .HasForeignKey("EmberUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ember.Domain.EmberEntities.Content", "ParentContent")
                        .WithMany("ChildContents")
                        .HasForeignKey("ParentContentId");

                    b.Navigation("ContentFormat");

                    b.Navigation("ContentType");

                    b.Navigation("ContentVisibility");

                    b.Navigation("EmberUser");

                    b.Navigation("ParentContent");
                });

            modelBuilder.Entity("Ember.Domain.EmberEntities.ContentCollection", b =>
                {
                    b.HasOne("Ember.Domain.Data.EmberUser", "EmberUser")
                        .WithMany()
                        .HasForeignKey("EmberUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmberUser");
                });

            modelBuilder.Entity("Ember.Domain.EmberEntities.ContentCollectionItem", b =>
                {
                    b.HasOne("Ember.Domain.EmberEntities.ContentCollection", "Collection")
                        .WithMany("CollectionItems")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ember.Domain.EmberEntities.Content", "Content")
                        .WithMany()
                        .HasForeignKey("ContentId");

                    b.Navigation("Collection");

                    b.Navigation("Content");
                });

            modelBuilder.Entity("Ember.Domain.EmberEntities.ContentInteraction", b =>
                {
                    b.HasOne("Ember.Domain.EmberEntities.Content", "Content")
                        .WithMany()
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ember.Domain.Data.EmberUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Content");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ember.Domain.EmberEntities.RelatedContent", b =>
                {
                    b.HasOne("Ember.Domain.EmberEntities.Content", "Content")
                        .WithMany()
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ember.Domain.EmberEntities.Content", "RelatedContentItem")
                        .WithMany()
                        .HasForeignKey("RelatedContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ember.Domain.EmberEntities.RelatedContentType", "RelatedContentType")
                        .WithMany()
                        .HasForeignKey("RelatedContentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Content");

                    b.Navigation("RelatedContentItem");

                    b.Navigation("RelatedContentType");
                });

            modelBuilder.Entity("Ember.Domain.EmberEntities.Tag", b =>
                {
                    b.HasOne("Ember.Domain.Data.EmberUser", "EmberUser")
                        .WithMany()
                        .HasForeignKey("EmberUserId");

                    b.Navigation("EmberUser");
                });

            modelBuilder.Entity("Ember.Domain.EmberEntities.TagItem", b =>
                {
                    b.HasOne("Ember.Domain.EmberEntities.ContentCollection", "Collection")
                        .WithMany()
                        .HasForeignKey("CollectionId");

                    b.HasOne("Ember.Domain.EmberEntities.Content", "Content")
                        .WithMany()
                        .HasForeignKey("ContentId");

                    b.HasOne("Ember.Domain.Data.EmberUser", "EmberUser")
                        .WithMany()
                        .HasForeignKey("EmberUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ember.Domain.EmberEntities.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collection");

                    b.Navigation("Content");

                    b.Navigation("EmberUser");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Ember.Domain.Data.EmberUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ember.Domain.Data.EmberRole", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Ember.Domain.Data.EmberUser", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Ember.Domain.EmberEntities.Content", b =>
                {
                    b.Navigation("ChildContents");
                });

            modelBuilder.Entity("Ember.Domain.EmberEntities.ContentCollection", b =>
                {
                    b.Navigation("CollectionItems");
                });
#pragma warning restore 612, 618
        }
    }
}
